/**
 * O catálogo das permissões reconhecidas pelo sistema.
 *
 * Declaração única no repositório (ADR-0027 §17): a carga inicial, os testes e todo
 * código que exigir uma permissão derivam daqui. O requisito funcional de origem de
 * cada permissão está no comentário ao lado (ADR-0014 §6, §7).
 *
 * A correspondência com a URS §2.3 é verificada pelo comando de conferência
 * (ADR-0027 §18), e não por este arquivo. Ver `pnpm run docs:check-catalog`.
 */
export const PERMISSION = {
  PERMISSION_GRANT_CREATE: 'PERMISSION_GRANT:CREATE', // RF-ACS-006
  PERMISSION_GRANT_REVOKE: 'PERMISSION_GRANT:REVOKE', // RF-ACS-007
  PERMISSION_GRANT_READ: 'PERMISSION_GRANT:READ', // RF-ACS-008

  INSTITUTION_CREATE: 'INSTITUTION:CREATE', // RF-INS-001
  INSTITUTION_READ: 'INSTITUTION:READ', // RF-INS-001
  INSTITUTION_UPDATE: 'INSTITUTION:UPDATE', // RF-INS-001
  INSTITUTION_DEACTIVATE: 'INSTITUTION:DEACTIVATE', // RF-INS-001
  INSTITUTION_ASSIGN_ADMIN: 'INSTITUTION:ASSIGN_ADMIN', // RF-INS-002
  INSTITUTION_REVOKE_ADMIN: 'INSTITUTION:REVOKE_ADMIN', // RF-INS-002

  COURSE_CREATE: 'COURSE:CREATE', // RF-CUR-001
  COURSE_READ: 'COURSE:READ', // RF-CUR-001
  COURSE_UPDATE: 'COURSE:UPDATE', // RF-CUR-001
  COURSE_DEACTIVATE: 'COURSE:DEACTIVATE', // RF-CUR-001
  COURSE_ASSIGN_COORDINATOR: 'COURSE:ASSIGN_COORDINATOR', // RF-CUR-002
  COURSE_REVOKE_COORDINATOR: 'COURSE:REVOKE_COORDINATOR', // RF-CUR-002

  COHORT_CREATE: 'COHORT:CREATE', // RF-TUR-001
  COHORT_READ: 'COHORT:READ', // RF-TUR-001
  COHORT_UPDATE: 'COHORT:UPDATE', // RF-TUR-001
  COHORT_DEACTIVATE: 'COHORT:DEACTIVATE', // RF-TUR-001
  COHORT_ASSIGN_PROFESSOR: 'COHORT:ASSIGN_PROFESSOR', // RF-TUR-002
  COHORT_REVOKE_PROFESSOR: 'COHORT:REVOKE_PROFESSOR', // RF-TUR-002

  ENROLLMENT_CREATE: 'ENROLLMENT:CREATE', // RF-TUR-003
  ENROLLMENT_READ: 'ENROLLMENT:READ', // RF-TUR-003

  INVITATION_CREATE: 'INVITATION:CREATE', // RF-TUR-004
  INVITATION_READ: 'INVITATION:READ', // RF-TUR-004
  INVITATION_REVOKE: 'INVITATION:REVOKE', // RF-TUR-004

  EVENT_CREATE: 'EVENT:CREATE', // RF-EVT-001
  EVENT_READ: 'EVENT:READ', // RF-EVT-001, RF-EVT-004
  EVENT_UPDATE: 'EVENT:UPDATE', // RF-EVT-001
  EVENT_CANCEL: 'EVENT:CANCEL', // RF-EVT-001

  MILESTONE_CREATE: 'MILESTONE:CREATE', // RF-EVT-002
  MILESTONE_READ: 'MILESTONE:READ', // RF-EVT-002
  MILESTONE_UPDATE: 'MILESTONE:UPDATE', // RF-EVT-002
  MILESTONE_DELETE: 'MILESTONE:DELETE', // RF-EVT-002

  EVENT_ASSIGN_ADVISOR: 'EVENT:ASSIGN_ADVISOR', // RF-EVT-003
  EVENT_REVOKE_ADVISOR: 'EVENT:REVOKE_ADVISOR', // RF-EVT-003

  TEAM_CREATE: 'TEAM:CREATE', // RF-EQP-001
  TEAM_READ: 'TEAM:READ', // RF-EQP-006
  TEAM_JOIN: 'TEAM:JOIN', // RF-EQP-002
  TEAM_ASSIGN_MEMBER: 'TEAM:ASSIGN_MEMBER', // RF-EQP-003
  TEAM_REMOVE_MEMBER: 'TEAM:REMOVE_MEMBER', // RF-EQP-003
  TEAM_INVITE_MEMBER: 'TEAM:INVITE_MEMBER', // RF-EQP-004
  TEAM_ASSIGN_ADVISOR: 'TEAM:ASSIGN_ADVISOR', // RF-EQP-005
  TEAM_REVOKE_ADVISOR: 'TEAM:REVOKE_ADVISOR', // RF-EQP-005

  ARTICLE_READ: 'ARTICLE:READ', // RF-ART-001
  ARTICLE_GRADE: 'ARTICLE:GRADE', // RF-ART-002
  ARTICLE_GRADE_MEMBER: 'ARTICLE:GRADE_MEMBER', // RF-ART-003

  PUBLICATION_CREATE: 'PUBLICATION:CREATE', // RF-ART-004
  PUBLICATION_READ: 'PUBLICATION:READ', // RF-ART-004
  PUBLICATION_UPDATE: 'PUBLICATION:UPDATE', // RF-ART-004
  PUBLICATION_DELETE: 'PUBLICATION:DELETE', // RF-ART-004

  TEMPLATE_CREATE: 'TEMPLATE:CREATE', // RF-TPL-001
  TEMPLATE_READ: 'TEMPLATE:READ', // RF-TPL-001, RF-TPL-002
  TEMPLATE_UPDATE: 'TEMPLATE:UPDATE', // RF-TPL-001
  TEMPLATE_DEACTIVATE: 'TEMPLATE:DEACTIVATE', // RF-TPL-001

  ARTICLE_EDIT: 'ARTICLE:EDIT', // RF-EDT-001, RF-EDT-002
  ARTICLE_FORMAT: 'ARTICLE:FORMAT', // RF-EDT-005
  ARTICLE_IMPORT: 'ARTICLE:IMPORT', // RF-EDT-006
  ARTICLE_EXPORT: 'ARTICLE:EXPORT', // RF-EDT-007
  ARTICLE_READ_HISTORY: 'ARTICLE:READ_HISTORY', // RF-EDT-008
  ARTICLE_RESTORE_VERSION: 'ARTICLE:RESTORE_VERSION', // RF-EDT-008
  ARTICLE_RETURN: 'ARTICLE:RETURN', // RF-REV-006
  ARTICLE_CONCLUDE: 'ARTICLE:CONCLUDE', // RF-REV-011

  REFERENCE_CREATE: 'REFERENCE:CREATE', // RF-EDT-003
  REFERENCE_READ: 'REFERENCE:READ', // RF-EDT-003
  REFERENCE_UPDATE: 'REFERENCE:UPDATE', // RF-EDT-003
  REFERENCE_DELETE: 'REFERENCE:DELETE', // RF-EDT-003
  REFERENCE_CITE: 'REFERENCE:CITE', // RF-EDT-004

  SUBMISSION_CREATE: 'SUBMISSION:CREATE', // RF-REV-001
  SUBMISSION_READ: 'SUBMISSION:READ', // RF-REV-001
  SUBMISSION_REVOKE: 'SUBMISSION:REVOKE', // RF-REV-002
  SUBMISSION_COMPARE: 'SUBMISSION:COMPARE', // RF-REV-010

  REMARK_CREATE: 'REMARK:CREATE', // RF-REV-004
  REMARK_READ: 'REMARK:READ', // RF-REV-004, RF-REV-009
  REMARK_UPDATE: 'REMARK:UPDATE', // RF-REV-005
  REMARK_ADDRESS: 'REMARK:ADDRESS', // RF-REV-007
  REMARK_RESOLVE: 'REMARK:RESOLVE', // RF-REV-008
  REMARK_REOPEN: 'REMARK:REOPEN', // RF-REV-008
  REMARK_DISMISS: 'REMARK:DISMISS', // RF-REV-008

  MESSAGE_CREATE: 'MESSAGE:CREATE', // RF-DSC-001, RF-DSC-003
  MESSAGE_READ: 'MESSAGE:READ', // RF-DSC-001, RF-DSC-004
  MESSAGE_REPLY: 'MESSAGE:REPLY', // RF-DSC-002
  MESSAGE_DELETE: 'MESSAGE:DELETE', // RF-DSC-001

  NOTIFICATION_READ: 'NOTIFICATION:READ', // RF-DSC-005
  NOTIFICATION_MARK_READ: 'NOTIFICATION:MARK_READ', // RF-DSC-006

  AI_SUMMARY_READ: 'AI_SUMMARY:READ', // RF-IAA-001

  COMPLIANCE_CHECK_REQUEST: 'COMPLIANCE_CHECK:REQUEST', // RF-IAA-002
  COMPLIANCE_CHECK_READ: 'COMPLIANCE_CHECK:READ', // RF-IAA-002

  SIMILARITY_CHECK_REQUEST: 'SIMILARITY_CHECK:REQUEST', // RF-IAA-003
  SIMILARITY_CHECK_READ: 'SIMILARITY_CHECK:READ', // RF-IAA-003

  AUTHORSHIP_SIGNAL_READ: 'AUTHORSHIP_SIGNAL:READ', // RF-IAA-004

  INSTITUTION_CONSENT_AI: 'INSTITUTION:CONSENT_AI', // RF-IAA-005

  PROGRESS_READ: 'PROGRESS:READ', // RF-ACP-001, RF-ACP-002

  RISK_SIGNAL_READ: 'RISK_SIGNAL:READ', // RF-ACP-003

  CONTRIBUTION_READ: 'CONTRIBUTION:READ', // RF-ACP-004

  REPORT_GENERATE: 'REPORT:GENERATE', // RF-ACP-005
  REPORT_READ: 'REPORT:READ', // RF-ACP-005
  REPORT_EXPORT: 'REPORT:EXPORT', // RF-ACP-006
} as const;

/** Código de permissão reconhecido. Texto no formato `RECURSO:ACAO` (ADR-0014 §2). */
export type PermissionCode = (typeof PERMISSION)[keyof typeof PERMISSION];

/** O catálogo inteiro, na ordem de declaração. */
export const PERMISSION_CODES: readonly PermissionCode[] = Object.values(PERMISSION);
